// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCLxTsNoKlKt8va9pfWtE_CYWOSw7ghHY',
    appId: '1:805139776505:web:d3a589cf06496db79d3328',
    messagingSenderId: '805139776505',
    projectId: 'flutterauth-df9c4',
    authDomain: 'flutterauth-df9c4.firebaseapp.com',
    storageBucket: 'flutterauth-df9c4.firebasestorage.app',
    measurementId: 'G-CHHVN4YEXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJgTt5RdpDhnY_se-FSIjfqH7Us_BOgA',
    appId: '1:805139776505:android:637e27e997a433899d3328',
    messagingSenderId: '805139776505',
    projectId: 'flutterauth-df9c4',
    storageBucket: 'flutterauth-df9c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdT4lidw4erBngREvAA2iLC7mCWjVPGAU',
    appId: '1:805139776505:ios:20f1fa954fe4a5009d3328',
    messagingSenderId: '805139776505',
    projectId: 'flutterauth-df9c4',
    storageBucket: 'flutterauth-df9c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdT4lidw4erBngREvAA2iLC7mCWjVPGAU',
    appId: '1:805139776505:ios:20f1fa954fe4a5009d3328',
    messagingSenderId: '805139776505',
    projectId: 'flutterauth-df9c4',
    storageBucket: 'flutterauth-df9c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCLxTsNoKlKt8va9pfWtE_CYWOSw7ghHY',
    appId: '1:805139776505:web:e301cf6aa78b8bef9d3328',
    messagingSenderId: '805139776505',
    projectId: 'flutterauth-df9c4',
    authDomain: 'flutterauth-df9c4.firebaseapp.com',
    storageBucket: 'flutterauth-df9c4.firebasestorage.app',
    measurementId: 'G-EDH4MJQW1M',
  );
}
